apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: my-integration
spec:
  flows:
    - route:
        id: route-c6c7
        description: process filter and get scroll id
        nodePrefixId: route-6bd
        autoStartup: false
        from:
          id: from-21de
          uri: timer
          parameters:
            timerName: runOnce
            repeatCount: "1"
          steps:
            - setHeaders:
                id: setHeaders-43e2
                description: Headers for getting data
                headers:
                  - id: setHeader-7fa8
                    name: Authorization
                    expression:
                      constant:
                        id: constant-fbc4
                        expression: Basic ZWxhc3RpYzpzZk5Ga0liRHlmTjVRUHNRQVpWUw==
                  - id: setHeader-0719
                    name: Content-Type
                    expression:
                      constant:
                        id: constant-9c47
                        expression: application/json
            - setBody:
                id: setBody-a8d1
                description: Query data with scroll
                expression:
                  constant:
                    id: constant-dd7f
                    expression: "{\r\n  \"query\": {\r\n    \"match_all\": {}\r\n  },\r\n  \"scroll\": \"1m\",\r\n  \"size\": 1000\r\n}\r\n"
            - toD:
                id: toD-e49c
                description: Get data
                uri: http://172.27.16.1:9200/account/_search?scroll=1m
            - process:
                id: process-0bd4
                description: Get scroll id
                disabled: false
                ref: Getscroll
            - process:
                id: process-294b
                description: Filter and send to kafka
                ref: FilterData
            - to:
                id: to-392d
                uri: direct
                parameters:
                  name: ProcessFilterRoute
    - route:
        id: route-c180
        description: Process and send to Kafka
        nodePrefixId: route-aa0
        autoStartup: false
        from:
          id: from-9b14
          description: direct
          uri: direct
          parameters:
            name: ProcessFilterRoute
          steps:
            - log:
                id: log-22ea
                description: Check scroll id available
                message: "\"scroll : ${exchangeProperty.scroll_id} \""
            - setHeaders:
                id: setHeaders-4af2
                description: Headers for getting data
                headers:
                  - id: setHeader-4d66
                    name: Authorization
                    expression:
                      constant:
                        id: constant-2a81
                        expression: Basic ZWxhc3RpYzpzZk5Ga0liRHlmTjVRUHNRQVpWUw==
                  - id: setHeader-f58a
                    name: Content-Type
                    expression:
                      constant:
                        id: constant-1651
                        expression: application/json
            - setBody:
                id: setBody-fd55
                description: Query scroll
                expression:
                  simple:
                    id: simple-f35c
                    expression: |-
                      {
                                "scroll": "2m",
                                "scroll_id": "${exchangeProperty.scroll_id}"
                              }
            - toD:
                id: toD-227d
                description: HTTP to elasticsearch
                uri: http://172.27.16.1:9200/_search/scroll
            - process:
                id: process-f6cf
                description: Filter Account
                ref: FilterData
            - log:
                id: log-e17c
                description: Body log
                message: ${body}
            - to:
                id: to-edf9
                uri: micrometer
                parameters:
                  metricsType: counter
                  metricsName: process_message
                  increment: "10"
            - choice:
                id: choice-f54c
                when:
                  - id: when-6b4e
                    description: No data found
                    expression:
                      simple:
                        id: simple-d18b
                        expression: "\"${exchangeProperty.isEmpty}\""
                    steps:
                      - log:
                          id: log-5dae
                          description: Data found log
                          message: "\"No more data, stopping.\""
                      - stop:
                          id: stop-b75b
                otherwise:
                  id: otherwise-e3fb
                  description: No data found
                  steps:
                    - log:
                        id: log-1697
                        description: Data found log
                        message: "\" Data is still available\""
                    - delay:
                        id: delay-c427
                        description: Avoid getting too fast
                        expression:
                          simple:
                            id: simple-ffe0
                            expression: "1000"
                    - toD:
                        id: toD-f897
                        description: Call this route again
                        uri: direct:ProcessFilterRoute
            - log:
                id: log-9ee5
                description: success log
                message: "\"Scroll done.\""
    - route:
        id: route-4dac
        description: get scrollid based on alias
        nodePrefixId: route-4a1
        autoStartup: false
        from:
          id: from-143d
          uri: timer
          parameters:
            timerName: runOnce
            repeatCount: "1"
          steps:
            - setHeaders:
                id: setHeaders-98a6
                description: headers for collecting data
                headers:
                  - id: setHeader-e5ad
                    name: Authorization
                    expression:
                      constant:
                        id: constant-2385
                        expression: Basic ZWxhc3RpYzpzZk5Ga0liRHlmTjVRUHNRQVpWUw==
                  - id: setHeader-d2b9
                    name: Content-Type
                    expression:
                      simple:
                        id: simple-2fe3
                        expression: application/json
            - setBody:
                id: setBody-e0a4
                description: Query condition
                expression:
                  constant:
                    id: constant-964a
                    expression: |-
                      {
                        "query": {
                          "match_all": {}
                        },
                        "size": 10
                      }
            - toD:
                id: toD-15c6
                description: Get Data
                uri: http://172.27.16.1:9200/data/_search?scroll=1m
            - log:
                id: log-11a8
                message: ${body}
            - process:
                id: process-72ac
                description: Get ScrollId
                ref: Getscroll
            - log:
                id: log-48f5
                description: log scroll id
                message: ${exchangeProperty.scroll_id}
            - process:
                id: process-8a10
                description: Add companyCode and save to DB
                ref: AddCompanyCode
            - to:
                id: to-2ecb
                uri: direct
                parameters:
                  name: GetAndSaveToDB
    - route:
        id: route-86d1
        description: Process and save to Mysql
        nodePrefixId: route-f47
        autoStartup: false
        from:
          id: from-9271
          uri: direct
          parameters:
            name: GetAndSaveToDB
          steps:
            - setHeaders:
                id: setHeaders-0a41
                headers:
                  - id: setHeader-fb8f
                    name: Authorization
                    expression:
                      constant:
                        id: constant-84f9
                        expression: Basic ZWxhc3RpYzpzZk5Ga0liRHlmTjVRUHNRQVpWUw==
                  - id: setHeader-088f
                    name: Content-Type
                    expression:
                      constant:
                        id: constant-d7d6
                        expression: application/json
            - setBody:
                id: setBody-40ac
                description: Set query with scrollid
                expression:
                  simple:
                    id: simple-141f
                    expression: |-
                      {
                                "scroll": "2m",
                                "scroll_id": "${exchangeProperty.scroll_id}"
                        }
            - toD:
                id: toD-3a57
                description: Get Data
                uri: http://172.27.16.1:9200/_search/scroll
            - process:
                id: process-9395
                description: Add companyCode and save to DB
                ref: AddCompanyCode
            - log:
                id: log-c950
                message: "\"Total processed: ${exchangeProperty.total_processed}\""
            - choice:
                id: choice-692e
                when:
                  - id: when-0631
                    description: No Data Found
                    expression:
                      simple:
                        id: simple-5acd
                        expression: "\"${exchangeProperty.isEmpty}\""
                    steps:
                      - stop:
                          id: stop-19b0
                      - log:
                          id: log-3e16
                          message: "\"No data found -> Stop process\""
                otherwise:
                  id: otherwise-f0eb
                  description: Data still available
                  steps:
                    - delay:
                        id: delay-3b39
                        description: Avoid getting data too fast
                        expression:
                          simple:
                            id: simple-ed1c
                            expression: "500"
                    - toD:
                        id: toD-495e
                        uri: direct:GetAndSaveToDB
            - log:
                id: log-7d63
                message: "\"success"
    - route:
        id: route-a57d
        description: Set Offset
        nodePrefixId: route-13e
        autoStartup: true
        from:
          id: from-9489
          uri: timer
          parameters:
            timerName: test
            repeatCount: "1"
          steps:
            - setProperty:
                id: setProperty-fe1d
                description: set default offset
                name: offset
                expression:
                  simple:
                    id: simple-6e31
                    expression: "0"
            - setProperty:
                id: setProperty-127e
                description: set total processed
                name: total_processed
                expression:
                  simple:
                    id: simple-cdd4
                    expression: "0"
            - log:
                id: log-c79e
                message: "\"offset:  ${exchangeProperty.offset}\"\r\n\"first total_processed: ${exchangeProperty.total_processed}\""
            - to:
                id: to-3c32
                description: setOffsetDirect
                uri: direct
                parameters:
                  name: ProcessAndSendKafka
    - route:
        id: route-c2b6
        description: Process DB and Kafka
        nodePrefixId: route-a18
        autoStartup: true
        from:
          id: from-889b
          uri: direct
          parameters:
            name: ProcessAndSendKafka
          steps:
            - process:
                id: process-caec
                description: Get Data from DB and Send to Kafka
                ref: MysqltoKafka
            - log:
                id: log-987f
                message: "\"Total Processed :${exchangeProperty.total_processed}\"\r\n\"IsEmpty: ${exchangeProperty.isEmpty}\""
            - choice:
                id: choice-c88a
                when:
                  - id: when-a781
                    expression:
                      simple:
                        id: simple-aa06
                        expression: ${exchangeProperty.isEmpty}
                    steps:
                      - stop:
                          id: stop-bca0
                otherwise:
                  id: otherwise-431a
                  steps:
                    - delay:
                        id: delay-3af5
                        expression:
                          simple:
                            id: simple-4ea7
                            expression: "3000"
                    - toD:
                        id: toD-d26d
                        uri: direct:ProcessAndSendKafka
            - log:
                id: log-b785
                description: Process Data Succesfully
                message: "\"Process Data Successfully\""
    - routeConfiguration: {}
    - routeConfiguration: {}
  dependencies:
    - mvn:mysql:mysql-connector-java:8.0.33
