apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: my-integration
spec:
  flows:
    - route:
        id: route-c6c7
        description: process filter and get scroll id
        nodePrefixId: route-6bd
        autoStartup: false
        from:
          id: from-21de
          uri: timer
          parameters:
            timerName: runOnce
            repeatCount: "1"
          steps:
            - setHeaders:
                id: setHeaders-43e2
                description: Headers for getting data
                headers:
                  - id: setHeader-7fa8
                    name: Authorization
                    expression:
                      constant:
                        id: constant-fbc4
                        expression: Basic ZWxhc3RpYzpzZk5Ga0liRHlmTjVRUHNRQVpWUw==
                  - id: setHeader-0719
                    name: Content-Type
                    expression:
                      constant:
                        id: constant-9c47
                        expression: application/json
            - setBody:
                id: setBody-a8d1
                description: Query data with scroll
                expression:
                  constant:
                    id: constant-dd7f
                    expression: "{\r\n  \"query\": {\r\n    \"match_all\": {}\r\n  },\r\n  \"scroll\": \"1m\",\r\n  \"size\": 1000\r\n}\r\n"
            - toD:
                id: toD-e49c
                description: Get data
                uri: http://172.27.16.1:9200/account/_search?scroll=1m
            - process:
                id: process-0bd4
                description: Get scroll id
                disabled: false
                ref: Getscroll
            - process:
                id: process-294b
                description: Filter and send to kafka
                ref: FilterData
            - to:
                id: to-392d
                uri: direct
                parameters:
                  name: ProcessFilterRoute
    - route:
        id: route-c180
        description: Process and send to Kafka
        nodePrefixId: route-aa0
        autoStartup: false
        from:
          id: from-9b14
          description: direct
          uri: direct
          parameters:
            name: ProcessFilterRoute
          steps:
            - log:
                id: log-22ea
                description: Check scroll id available
                message: "\"scroll : ${exchangeProperty.scroll_id} \""
            - setHeaders:
                id: setHeaders-4af2
                description: Headers for getting data
                headers:
                  - id: setHeader-4d66
                    name: Authorization
                    expression:
                      constant:
                        id: constant-2a81
                        expression: Basic ZWxhc3RpYzpzZk5Ga0liRHlmTjVRUHNRQVpWUw==
                  - id: setHeader-f58a
                    name: Content-Type
                    expression:
                      constant:
                        id: constant-1651
                        expression: application/json
            - setBody:
                id: setBody-fd55
                description: Query scroll
                expression:
                  simple:
                    id: simple-f35c
                    expression: |-
                      {
                                "scroll": "2m",
                                "scroll_id": "${exchangeProperty.scroll_id}"
                              }
            - toD:
                id: toD-227d
                description: HTTP to elasticsearch
                uri: http://172.27.16.1:9200/_search/scroll
            - process:
                id: process-f6cf
                description: Filter Account
                ref: FilterData
            - log:
                id: log-e17c
                description: Body log
                message: ${body}
            - to:
                id: to-edf9
                uri: micrometer
                parameters:
                  metricsType: counter
                  metricsName: process_message
                  increment: "10"
            - choice:
                id: choice-f54c
                when:
                  - id: when-6b4e
                    description: No data found
                    expression:
                      simple:
                        id: simple-d18b
                        expression: "\"${exchangeProperty.isEmpty}\""
                    steps:
                      - log:
                          id: log-5dae
                          description: Data found log
                          message: "\"No more data, stopping.\""
                      - stop:
                          id: stop-b75b
                otherwise:
                  id: otherwise-e3fb
                  description: No data found
                  steps:
                    - log:
                        id: log-1697
                        description: Data found log
                        message: "\" Data is still available\""
                    - delay:
                        id: delay-c427
                        description: Avoid getting too fast
                        expression:
                          simple:
                            id: simple-ffe0
                            expression: "1000"
                    - toD:
                        id: toD-f897
                        description: Call this route again
                        uri: direct:ProcessFilterRoute
            - log:
                id: log-9ee5
                description: success log
                message: "\"Scroll done.\""
    - route:
        id: route-c55e
        description: get scroll id and process data
        nodePrefixId: route-a25
        autoStartup: true
        from:
          id: from-e2ab
          uri: timer
          parameters:
            repeatCount: "1"
            timerName: runOnce
          steps:
            - setProperty:
                id: setProperty-2802
                description: Set total processed
                name: total_processed
                expression:
                  simple:
                    id: simple-1dd4
                    expression: "0"
            - setHeaders:
                id: setHeaders-ea8a
                description: Headers for getting data
                headers:
                  - id: setHeader-1620
                    name: Authorization
                    expression:
                      constant:
                        id: constant-b2a4
                        expression: Basic ZWxhc3RpYzpzZk5Ga0liRHlmTjVRUHNRQVpWUw==
                  - id: setHeader-f40a
                    name: Content-Type
                    expression:
                      constant:
                        id: constant-d1c1
                        expression: application/json
            - setBody:
                id: setBody-120e
                description: Query to get data
                expression:
                  simple:
                    id: simple-3581
                    expression: "{\r\n  \"query\": {\r\n    \"match_all\": {}\r\n  },\r\n  \"scroll\": \"1m\",\r\n  \"size\": 10\r\n}\r\n"
            - toD:
                id: toD-7d52
                uri: http://172.27.16.1:9200/data/_search?scroll=1m
            - process:
                id: process-dde8
                description: Get Scroll Id
                ref: Getscroll
            - process:
                id: process-9f2a
                description: Process Mysql query and send data to Kafka
                ref: ProcessQueryAndSendtoKafka
            - to:
                id: to-8d15
                uri: direct
                parameters:
                  name: ProcessCompanyContinuously
    - route:
        id: route-7245
        description: Process Company Code And Send to Kafka
        nodePrefixId: route-af2
        autoStartup: true
        from:
          id: from-17aa
          uri: direct
          parameters:
            name: ProcessCompanyContinuously
          steps:
            - setHeaders:
                id: setHeaders-468e
                headers:
                  - id: setHeader-7d41
                    name: Authorization
                    expression:
                      constant:
                        id: constant-6555
                        expression: Basic ZWxhc3RpYzpzZk5Ga0liRHlmTjVRUHNRQVpWUw==
                  - id: setHeader-d5cb
                    disabled: Content-Type
                    name: Content-Type
                    expression:
                      constant:
                        id: constant-23f0
                        expression: application/json
            - setBody:
                id: setBody-5da9
                expression:
                  simple:
                    id: simple-f6ca
                    expression: |-
                      {
                                "scroll": "2m",
                                "scroll_id": "${exchangeProperty.scroll_id}"
                              }
            - toD:
                id: toD-e261
                uri: http://172.27.16.1:9200/_search/scroll
            - process:
                id: process-07d6
                description: ProcessQueryAndSendtoKafka
                ref: ProcessQueryAndSendtoKafka
            - log:
                id: log-a745
                message: "\"Total processed:  ${exchangeProperty.total_processed}\""
            - choice:
                id: choice-4f6c
                when:
                  - id: when-42c6
                    expression:
                      simple:
                        id: simple-8059
                        expression: ${exchangeProperty.isEmpty}
                    steps:
                      - log:
                          id: log-506a
                          message: "\"Data is empty, stop route\""
                      - stop:
                          id: stop-1862
                otherwise:
                  id: otherwise-8e4c
                  steps:
                    - log:
                        id: log-f262
                        message: "\"Still have data to process \""
                    - toD:
                        id: toD-f29f
                        uri: direct:ProcessCompanyContinuously
    - routeConfiguration: {}
    - routeConfiguration: {}
  dependencies:
    - mvn:mysql:mysql-connector-java:8.0.33
